### ISSUE TITLE
Issues while setting up Rails template in new project

### ISSUE THREAD

**Issue by CaraHill** [ackama/rails-template#100]
I ran in to the following when setting up a new Rails project with this template - some might just be related to issues with my own dev setup, but Eoin thought it was worth creating an issue here as other people might run into something similar, and we might be able to add to the script to remind people to ensure these things are set as required (or at least add to the ReadMe).

1. When I first tried to the Rails new ... command with all of the options for the template, I got some general Ruby errors. Though I had 2.5.0 installed, I had to reinstall and set locally to resolve.

2. I had Rails ~5.3 installed in the folder I was running the command in, and needed Rails 6. I know this was in the ReadMe, but I hadn't checked before so had to stop and update Rails to resolve.

3. Next, I had an issue with the pg gem that made the script top running - I had to gem install to resolve and then start over.

4. I had the wrong version of Node. I had to set to 10 and then start over.

5. 🐘 I gave the script `https://github.com:ackama/PROJECT-REPO.git` when it asked for the remote git repo, but should have given the SSH version. Maybe the script could give an example that indicates this should be the SSH version? eg. `[git@github.com:USERNAME/PROJECT-REPO.git]`

**Comment by joshmcarthur** [comment]
@CaraHill I'll number my ideas to match them up to the problems.

1. Can you recall what the errors were? It would be good to know if these errors were because of some special new syntax we're using somewhere, or some kind of environment issue.
2. I suspect that there's a feature here where we could perhaps check with the user (or at least warn them), if they're not using the _latest_ version of Rails when they create the application.
3. Again, do you know what the problem with the pg gem was?
4. Similar to point 2 - I'm unsure if we want to have a hardcoded version of Node we require, but perhaps we should try and find out what the latest Node LTS version is, and warn or require confirmation if the user doesn't have that set up.
5. Ideally I think it would be best if the template could handle HTTPS OR SSH git remotes. How did the HTTPS remote fail? Is there something we could do to just have this work, rather than locking down the format?
