### ISSUE TITLE
Is overcommit right for this template?

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#111]
I personally don't feel like I get a lot of value from git hook checks on the projects I'm on. I'm happy to go with whatever the consensus is but here's my reasoning:

### Costs

1. We have linters for everything anyway (so overcommit isn't actually doing new checks) - CI will catch any code issues before anybody else sees them.
1. Overcommit really gets in the way sometimes when you are working on a spike or doing some ops/CI change that requires a lot of commit & push flow.
1. Git hooks don't play particularly nicely with Git GUIs e.g. SourceTree makes me do a lot of clicking to find out _why_ overcommit was sad if a commit fails
1. The cross-platform issues outlined by @G-Rath on PR #105 

### Benefits

1. The only benefit I see is that it should reduce the number of `Fixup rubocop` commits. I say _reduce_ not _eliminate_ because on larger projects (where rubocop takes a while to fun) I started adding `-n` to git command to skip hooks because running them was just annoying in my context.

While it's always possible for me to just be lazy, a few contexts where this makes sense are when you are committing a lot on a spike or trying to sort out some ops/CI issue which requires a lot of commits and the slowness becomes grating.

### Summary

I don't think the benefits are worth the cost of adding lots of friction to the `git commit` flow for _most projects_.

I think that we should remove it from the template and let teams opt-in to it if it makes sense for their use-case.

**Comment by joshmcarthur** [comment]
I would at least like to have a variant for it. I wouldn't be without it now on _any_ project I work on, including my own. I'm not particularly fussed about what tool we use, but in my experience, the incidence of "fix linting error" commits I see falls to practically zero. It additionally catches things that are genuinely_not_ caught in CI, such as a failure to check in a schema.rb change. 

I agree that there's an overhead to running these checks. One thing we could investigate is whether there is a way we could speed this up - perhaps to run checks in parallel?

I think that given it _is_ optional, having it on by default for developers who maybe _don't_ have the experience to assess whether those checks should be running or not before CI catches it makes sense. If you don't want to use it - that's fine - the hooks don't force themselves to install AFAIK, we just install them as part of the set up (e.g. we could skip them using an env var)

**Comment by joshmcarthur** [comment]
An additional note - in a context where we're working with a visible commit log (visible to clients, other devs or public), I think there's a lot of value in the professionalism addded when the commits to a branch are logical "Add xyz behaviour for TICKET-123" commits, rather than a few of these and several dozen more "rubocop", "Fix linting errors", "lint". Which actually raises another point - overcommit catching these means a higher quality of commit messages, generally - precisely because linter errors are hard to explain, and so, by the 4th or 5th swing at getting rubocop to pass in CI, devs are down from the most descriptive commit message I've seen for linter resolution (unfortunately) "Fix rubocop warnings relating to Metrics/LineLength" to something way worse, like "rubocop", or "fix linter". If rebasing was part of our workflow, then this wouldn't be so bad, but it isn't, so ultimately we're going to end up with those commits on a main branch.

**Comment by joshmcarthur** [comment]
To clarify - I'm not committed to keeping overcommit, but I would like some kind of pre-commit scanner. If something like Husky worked better cross-platform, that would 100% fill my needs. The problem with Husky of course is that it then requires JS to be set up and around, which isn't always the case either :-)

**Comment by eoinkelly** [comment]
Would something like https://github.com/Arkweid/lefthook be worth a look? (git hook thingy written in go)

**Comment by G-Rath** [comment]
While I like what it's doing, I feel it's a bit heavy handed to install it automatically as part of our default setup (which is why `overcommit` itself doesn't), and I find it more than doubles the time it takes for me to run git commands even when it's not doing checks (i.e `git checkout .`, because we *might* have a hook configured and so it needs to spin up a whole ruby process).

Overall I'm a fan of using git hooks to head off CI checks that will fail, so more than happy to explore alternatives. I know `husky` works well as using bash as it's entry point means we can shim `node` in Windows to call out to `wsl`: 

```
# windows shim of node that is called by run_node

cmd '/C C:\Users\G-Rath\AppData\Local\Microsoft\WindowsApps\ubuntu.exe run "/home/g-rath/.nodenv/shims/node"' $@
```

I'll have a look at lefthook and see how it behaves.

> overcommit catching these means a higher quality of commit messages

I agree with this in principle, but also think its a problem that's bigger than the scope of this issue/discussion, which is that we should start getting serious about improving our git professionalism, which I feel the first step to that is in education & discussion) rather than adding a tool that starts yelling at you (or actually just warns you, which I think equates to it might as well not being there: when overcommits spits out warnings about commit messages, GUIs typically never show them since the commit was successful, and in the cli devs usually overlook such messages as they're not blocking).

The example you provided is a great one that I would love to see improved, but in that situation I think it would be better to start blocking PRs with a request for the commits to be squashed or rebased, and educate the author on how to do that if they're unsure.

Finally, we can always merge with squash: we want to have nice small commits and PRs that add specific features, so having the commits squashed into one (especially if the majority of them are "fixed lint errors") I don't think harms the project .

**Comment by eoinkelly** [comment]
Closing because we don't have any consensus on the action proposed by this issue. I agree there is a bigger discussion to be had but the comments on this issue probably isn't the right forum.
