### ISSUE TITLE
dotenv-webpack jS package needs to be in dependencies not devDependencies

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#115]
Assets precompilation runs on production boxes so it needs to be installed by `yarn install`

**Comment by G-Rath** [comment]
I don't think this is the end of the world, but would like to consider the alternative of using `yarn install --production=false`.

We hit this in apvi, which uses a lot more devDependencies (i.e eslint & prettier as it runs them via webpack plugins, `cross-spawn` as it's calling a script, etc), where you'd end up moving pretty much all of your `devDependencies` into `dependencies`.

`@rails/webpacker` abstracts a lot of the standard devDependencies like `webpack` & `babel` away, but I'm wondering if we should explore using `yarn install --production=false` (which is what I did in apvi).

Typically the reason this is done is to shave off a few seconds in the install time, and to reduce the disk space requirements a little, both of which are usually minor gains; we can always run `yarn install --production=true` after the precompilation to prune the tree to reclaim the disk space.

-----

I guess really this comes down to what line of thinking do we want to encourage? There are some schools of thought (i.e Vue & React do this) that in this situation everything should go into `devDependencies`, since the build tools bundle everything up and so none of the dependencies are "required" at runtime.

**Comment by fractalcactus** [comment]
Hello there, what action should we take?

**Comment by eoinkelly** [comment]
@G-Rath That is an interesting point. I think we should make a separate issue to discuss how we want to use `dependencies` vs `devDependencies` and let this issue focus on fixing the bug that the rails apps we currently generate cannot compile assets in production environments.

@G-Rath are you ok to create that other issue and outline your thinking about it?
