### ISSUE TITLE
Consider updating Github Action CI matrix to test on Windows and macOS as well as linux

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#122]
PR #121 is moving us to Github Actions. This would allow us to test the template on macOS and Windows too if we want to.

**Comment by G-Rath** [comment]
Had a discussion w/ @fractalcactus IRL, where we discussed what this involved. The main point was that it's probably best to do in two parts: first adding running against ubuntu & macOS, and then afterwards running on Windows because of the troubles that sometimes occur with gems that carry native dependencies running on Windows.

Should Windows prove to be a pain, we're happy to run against WSL instead, since we recommend that to devs working on Windows anyway.

**Comment by fractalcactus** [comment]
It is currently impossible to set up the OS matrix, because installing a postgres image requires a docker container, and:

> Note: If your workflows use Docker container actions or service containers, then you must use a Linux runner:
> 
> If you are using GitHub-hosted runners, you must use the ubuntu-latest runner.
> If you are using self-hosted runners, you must use a Linux machine as your runner and Docker must be installed
https://github.com/actions/virtual-environments/tree/main/images

The tools included in GitHub-hosted runners are updated weekly, so hopefully docker will be available on more than just `ubuntu-latest` soon, you can check [here](https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners) for when Docker Compose, Docker-Moby, and Docker-Buildx are added to other images
