### ISSUE TITLE
Use secure cookies by default

### ISSUE THREAD

**Issue by lamorrison** [ackama/rails-template#162]
Like this:

Rails.application.config.session_store :cookie_store, key: '_testapp_session', secure: true

This issue was created in response to a pen test report. We'd like to pass pen test criteria by default.

**Comment by JamesYang76** [comment]
Because `config.force_ssl` is true in production and staging environment, secure cookies is used by default in  production and staging environment. 
In development and test environment, secure cookies are not used by default.
I think  that we do not need to do `Rails.application.config.session_store :cookie_store, key: '_testapp_session', secure: true`

**Comment by eoinkelly** [comment]
Discussed with @lamorrison in person. It turns out the pen-test was referring to a cookie set by Cloudflare, not Rails. We have followed up with the team working on this. Thanks for verifying Rails behaviour @JamesYang76 

Closing this because no action to take for this template.
