### ISSUE TITLE
Add .envrc file to generated app

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#169]
Direnv https://direnv.net/ is a great tool and very popular among our devs who do a lot of ops work. We should add a `.envrc` file to the output of this template. As a starting suggestion, it could contain:

```sh
# ./.envrc

# load .env into the user's shell
dotenv

# add ./bin to PATH. Assuming the right binstubs existin in ./bin this means devs don't have to 
# type 'bundle exec' before each command
PATH_add bin

# add binaries installed by node to PATH
PATH_add node_modules/.bin
```

Direnv commands documented in https://direnv.net/man/direnv-stdlib.1.html

**Comment by eoinkelly** [comment]
We could add a commented out `export AWS_PROFILE=` line to give devs a suggestion about how to setup AWS access

**Comment by eoinkelly** [comment]
Do we want to encourage users to check `.envrc` into git? It would be useful to have it available to all team members but I feel a bit squeamish because it's a file which could eventually accumulate values which would differ between team members e.g. `AWS_PROFILE` env var is per machine.

**Comment by G-Rath** [comment]
No, I don't think that's something we should ever be encouraging both because as you say it could accumulate user-specific values but also because we recommend it as a way to clearly put secret values into your env without having to worry about different shells etc (especially in our infrastructure repos).

We can use `source_env` to source other files, so we could have something like a `common.envrc` but even then I don't think there's enough value due to the amount of user-specific variation that'll exist.

**Comment by eoinkelly** [comment]
I agree @G-Rath. If we are only generating `.envrc` for the one user who actually runs the template then I'm not sure this is worth doing anymore :shrug: . Add a :thumbsup: if you agree that I should close this issue, sing out in a comment if  you disagree

**Comment by eoinkelly** [comment]
We could add a section to the generated `README.md` suggesting that `direnv` is cool. Is that the better approach?

**Comment by eoinkelly** [comment]
We think direnv is cool but doesn't need to be part of this template
