### ISSUE TITLE
Refactoring to backend-base

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#174]
## Background

This template is conceptually a set of templates which work together. 

There is a "backend base template" which is loaded directly from `template.rb`. This template is always applied - it's files and directories live in the root of this repo.

Then there are some templates in `variants/` which are **always** applied e.g. `frontend-base`.

Then there are other templates in `variants/` which are applied only if the user requests it e.g. `devise`.

The "backend base template" isn't really any different to other variants except that its files are in the project root

## The proposed change

I think we should create `variants/backend-base` and move all the files related to that template into it.

This will achieve the following:

1. Make this repo more consistent - all templates are variants
1. Make it much clearer about which files in the project root are template files and which are for this repo itself

## The challenges

While the code change for this is fairly simple (mostly moving files around), it will mean that every PR which was started with the old code organisation and hasn't landed will need to be updated to modify the files in their new locations. This will be a fairly disruptive change. To mitigate this I'm happy to help work on your PR if it hasn't landed when this refactoring does.

@joshmcarthur and I discussed this a while back and agree this is a good step towards making the repo easier to work on.

Does anybody have reservations about this. Questions & comments welcome

**Comment by fractalcactus** [comment]
sounds good to me!

**Comment by JamesYang76** [comment]
First, I think `variants` directory is confusing because there are some templates(`accessibility`,` performance`, `frontend-base`) always applied and some others are not in `variants` directory. 

In my opinion, optional templates should be under `variants`, and  other templates are under `frontend-base` or `backend-base` which are same level with `variants`

Second, if move all the files related to that template into `backend-base`, I think almost all of directories should be moved into `backend-base`.
For example, `backend-base/app`, `backend-base/bin` and so on. Is it our intention?
