### ISSUE TITLE
Proprosal: replace the interactive code with a yml config file

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#236]
We have a lot of variants now and users are asked a lot of questions during installation. This is _ok_ but they don't really get any advance warning about the choices they will have to make and we don't currently provide them any context to help make the choice.

I'm thinking that we could instead use a `ackama-rails-template.yml` file which contains all the choices. 

1. User creates `ackama-rails-template.yml` in their current working dir
2. They copy from our example (either in `README.md` or a file in this repo) and fill out the choices as they see fit for their project. 
3. They run this rails template which picks up the file and implements their choices.

I see the following benefits of this:

1. Users get more notice about the choices they need to make - they don't have to make a quick decision about whether they need something like sidekiq or not.
2. We get to use those yml files during local development and running tests - it would make invoking a complex set of choices much clearer

All the details of this are up for discussion but I guess the first hurdle is whether we think this is a good idea or not.

Thoughts?

**Comment by G-Rath** [comment]
I like it! I also think there's nothing really stopping us from doing both (and that that'd be a good thing to do).

I'm picturing something like:
  * we look for `ackama-rails-template.yaml`
    * -> if present: load that into a hash
    *  -> if missing: print "btw you can configure this using a yaml ..."
  * whenever we prompt, we first check if the hash contains the prompt value
     * -> if present: use that value
     * -> if missing: prompt the user
     * -> if `errorOnAbsentPromptValues` is `true`: error (name not final)
 * (optionally) after generating, prompt the user if they'd like to create/update a `ackama-rails-template.yaml` based on what they picked for future re-use (based on if they had to be asked any prompts)

That way users coming from what I imagine is the standard rails template flow of passing a git url to `--template` won't need to follow a two-step process, as well as making new prompts more discoverable since they'll either cause a prompt that the user will interact with or an error depending on their setting, rather than outputting a "hey we've got a new prompt" that could easily get lost (and would require us to decide to add that).

Plus I think it'd be super easy to support anyway 🤷 

By having `errorOnAbsentPromptValues`, that should make it easier for us to fail-fast i.e in CI systems so we don't have to worry about having tests timeout because they're waiting for an unexpected prompt.

----

We actually already do an env check when asking if we should apply a variant which I think could easily be refactored to check for specific env variables instead of just one + to support `false`; as a first step towards having more fine-grain control.

**Comment by eoinkelly** [comment]
This work has been completed in PR #282
