### ISSUE TITLE
Configuration option `use_typescript: true` only works with `apply_variant_react: true`

### ISSUE THREAD

**Issue by halles** [ackama/rails-template#408]
When creating a project using this template, the option `use_typescript: true` only renders a functional project when the option `apply_variant_react` is set to `true`.

Using `use_typescript: true` with `apply_variant_react: false` generates react files that do not pass linting and break the build
```
$ CONFIG_PATH=../ackama_rails_template.config.yml rails new my_app_skipjs_use_ts_noreact --no-rc --database=postgresql  --skip-action-mailbox --skip-action-cable --skip-javascript --template=https://raw.githubusercontent.com/ackama/rails-template/main/template.rb
```
```
[…]
$ prettier --write './**/*.{css,scss,json,md,js,ts,tsx,jsx}'
.auditapprc.json 12ms
.eslintrc.js 9ms
.stylelintrc.js 4ms
app/assets/config/manifest.js 2ms
app/frontend/packs/application.ts 96ms
app/frontend/stimulus/controllers/hello_controller.ts 5ms
app/frontend/stylesheets/_elements.scss 11ms
app/frontend/stylesheets/application.scss 3ms
config/webpack/webpack.config.js 4ms
package.json 4ms
README.md 44ms
✨  Done in 1.05s.
      append    bin/ci-run
       apply  /var/folders/qg/_p1yx7411vjcdbxxkncwqntc0000gn/T/rails-template-20221202-33057-bksera/variants/frontend-base/js-lint/fixes.rb
         run    yarn run js-lint-fix from "."
yarn run v1.22.19
$ eslint . --ignore-pattern '!.eslintrc.js' --ext js,ts,tsx,jsx --fix

/Users/xtc/Work/SolomAxe/my_app_skipjs_use_ts_noreact/app/frontend/stimulus/controllers/hello_controller.ts
  14:56  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
```

**Comment by G-Rath** [comment]
I'm a bit confused because you've said in the title that `use_typescript: true` only works when `apply_variant_react` is `true`, yet in your body you've said the opposite:

> Using use_typescript: true with apply_variant_react: true generates react files that do not pass linting and break the build

You've also then provided an output that is skipping react...

-----

Ultimately though what you've highlighted (and I think is what this issue is meant to be about) is that we don't have a test covering `basic-typescript` (aka `use_typescript` being `true` without either `use_react` or `use_bootstrap` being `true`) - let's create a PR with that and see what the result is 🙂

**Comment by G-Rath** [comment]
Discussed this in Slack with @halles - the actual problem is that the `frontend-stimulus` variant is TypeScript aware (i.e. it will create a `.ts` file instead of a `.js` one) but doesn't actually setup TypeScript properly, so if you don't also enable `apply_variant_react` or `apply_variant_bootstrap`, you end up with a broken app.

He's going to work on a `frontend-base-typescript` variant that encapsulates the common setup for TS that's currently being done by the react & bootstrap variants (and then their respective TypeScript variants will handle any specifics)
