### ISSUE TITLE
Consider gzipping Rails responses by default

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#418]
[This talk](https://www.youtube.com/watch?v=BmiVevOUvho) emphasised for me how important gzipping our content is. It's quite trivial to turn on in Rails - see [this article](https://www.schneems.com/2017/11/08/80-smaller-rails-footprint-with-rack-deflate/). 

I think we should consider adding `Rack::Deflater` as a default for our apps.

## Do CDNs do this for us already?

[AWS CloudFront will not reliably gzip dynamic content](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html). 
> CloudFront does not always compress dynamic content. Sometimes responses for dynamic content are compressed, and sometimes they are not.

I have not verified this but I _think_ [CloudFlare will compress dynamic content](https://developers.cloudflare.com/support/speed/optimization-file-size/what-will-cloudflare-compress/) but they state that they will honor gzipping done by the server:

> If you’re already using gzip we will honor your gzip settings as long as you’re passing the details in a header from your web server for the files.

**Comment by G-Rath** [comment]
I'm trying to figure out if it supports brotli encoding too, since that's even better than gzip and it sounds like a PR got merged [related to that](https://github.com/rack/rack/pull/1184) but the [code itself only seems to mention `gzip`?](https://github.com/rack/rack/blob/main/lib/rack/deflater.rb#L55C33-L56)

Still importantly it correct respects `Accept-Encoding` so clients that don't support it can tell the server that, so this sounds like a no-brainer? (and that we should do a followup looking into brotli/br support too)

**Comment by eoinkelly** [comment]
I'm going to try this on an app and report my findings here.
