### ISSUE TITLE
Rails 8: Do we want to use the solid_* gems as our defaults?

### ISSUE THREAD

**Issue by eoinkelly** [ackama/rails-template#568]
Rails 8 installs and uses the  solid_cache solid_queue solid_cable gems by default (in all envs). Are they our default now too? e.g. no redis by default for background jobs or rails cache?

**Comment by G-Rath** [comment]
I'm +1 on exploring these long-term, but for now I think we should keep things as-is because:
  - replacing `sidekiq` is a big thing from a history POV, so should be given its own PR
  - my understanding is right now `good_job` has a much richer feature set than `solid_queue` (though it looks like they might have already caught up)

**Comment by eoinkelly** [comment]
I agree with @G-Rath 's take. Even if we do adopt them, they should be separate PRs.
